import {MigrationInterface, QueryRunner} from "typeorm";

export class InsertBank1637453328119 implements MigrationInterface {

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query("INSERT INTO `bank` (`number`, `name`) VALUES (001,'001 - BANCO DO BRASIL S/A')");
        await queryRunner.query("INSERT INTO `bank` (`number`, `name`) VALUES (002,'002 - BANCO CENTRAL DO BRASIL')");
        await queryRunner.query("INSERT INTO `bank` (`number`, `name`) VALUES (003,'003 - BANCO DA AMAZONIA S.A.')");
        await queryRunner.query("INSERT INTO `bank` (`number`, `name`) VALUES (004,'004 - BANCO DO NORDESTE DO BRASIL S.A.')");
        await queryRunner.query("INSERT INTO `bank` (`number`, `name`) VALUES (007,'007 - BANCO NAC DESENV. ECO. SOCIAL S.A.')");
        await queryRunner.query("INSERT INTO `bank` (`number`, `name`) VALUES (008,'008 - BANCO MERIDIONAL DO BRASIL')");
        await queryRunner.query("INSERT INTO `bank` (`number`, `name`) VALUES (020,'020 - BANCO DO ESTADO DE ALAGOAS S.A.')");
        await queryRunner.query("INSERT INTO `bank` (`number`, `name`) VALUES (021,'021 - BANCO DO ESTADO DO ESPIRITO SANTO S.A.')");
        await queryRunner.query("INSERT INTO `bank` (`number`, `name`) VALUES (022,'022 - BANCO DE CREDITO REAL DE MINAS GERAIS SA')");
        await queryRunner.query("INSERT INTO `bank` (`number`, `name`) VALUES (024,'024 - BANCO DO ESTADO DE PERNAMBUCO')");
        await queryRunner.query("INSERT INTO `bank` (`number`, `name`) VALUES (025,'025 - BANCO ALFA S/A')");
        await queryRunner.query("INSERT INTO `bank` (`number`, `name`) VALUES (026,'026 - BANCO DO ESTADO DO ACRE S.A.')");
        await queryRunner.query("INSERT INTO `bank` (`number`, `name`) VALUES (027,'027 - BANCO DO ESTADO DE SANTA CATARINA S.A.')");
        await queryRunner.query("INSERT INTO `bank` (`number`, `name`) VALUES (028,'028 - BANCO DO ESTADO DA BAHIA S.A.')");
        await queryRunner.query("INSERT INTO `bank` (`number`, `name`) VALUES (029,'029 - BANCO DO ESTADO DO RIO DE JANEIRO S.A.')");
        await queryRunner.query("INSERT INTO `bank` (`number`, `name`) VALUES (030,'030 - BANCO DO ESTADO DA PARAIBA S.A.')");
        await queryRunner.query("INSERT INTO `bank` (`number`, `name`) VALUES (031,'031 - BANCO DO ESTADO DE GOIAS S.A.')");
        await queryRunner.query("INSERT INTO `bank` (`number`, `name`) VALUES (032,'032 - BANCO DO ESTADO DO MATO GROSSO S.A.')");
        await queryRunner.query("INSERT INTO `bank` (`number`, `name`) VALUES (033,'033 - BANCO DO ESTADO DE SAO PAULO S.A.')");
        await queryRunner.query("INSERT INTO `bank` (`number`, `name`) VALUES (034,'034 - BANCO DO ESADO DO AMAZONAS S.A.')");
        await queryRunner.query("INSERT INTO `bank` (`number`, `name`) VALUES (035,'035 - BANCO DO ESTADO DO CEARA S.A.')");
        await queryRunner.query("INSERT INTO `bank` (`number`, `name`) VALUES (036,'036 - BANCO DO ESTADO DO MARANHAO S.A.')");
        await queryRunner.query("INSERT INTO `bank` (`number`, `name`) VALUES (037,'037 - BANCO DO ESTADO DO PARA S.A.')");
        await queryRunner.query("INSERT INTO `bank` (`number`, `name`) VALUES (038,'038 - BANCO DO ESTADO DO PARANA S.A.')");
        await queryRunner.query("INSERT INTO `bank` (`number`, `name`) VALUES (039,'039 - BANCO DO ESTADO DO PIAUI S.A.')");
        await queryRunner.query("INSERT INTO `bank` (`number`, `name`) VALUES (041,'041 - BANCO DO ESTADO DO RIO GRANDE DO SUL S.A.')");
        await queryRunner.query("INSERT INTO `bank` (`number`, `name`) VALUES (047,'047 - BANCO DO ESTADO DE SERGIPE S.A.')");
        await queryRunner.query("INSERT INTO `bank` (`number`, `name`) VALUES (048,'048 - BANCO DO ESTADO DE MINAS GERAIS S.A.')");
        await queryRunner.query("INSERT INTO `bank` (`number`, `name`) VALUES (059,'059 - BANCO DO ESTADO DE RONDONIA S.A.')");
        await queryRunner.query("INSERT INTO `bank` (`number`, `name`) VALUES (070,'070 - BANCO DE BRASILIA S.A.')");
        await queryRunner.query("INSERT INTO `bank` (`number`, `name`) VALUES (077,'077 - BANCO INTER S.A.')");
        await queryRunner.query("INSERT INTO `bank` (`number`, `name`) VALUES (104,'104 - CAIXA ECONOMICA FEDERAL')");
        await queryRunner.query("INSERT INTO `bank` (`number`, `name`) VALUES (106,'106 - BANCO ITABANCO S.A.')");
        await queryRunner.query("INSERT INTO `bank` (`number`, `name`) VALUES (107,'107 - BANCO BBM S.A.')");
        await queryRunner.query("INSERT INTO `bank` (`number`, `name`) VALUES (109,'109 - BANCO CREDIBANCO S.A.')");
        await queryRunner.query("INSERT INTO `bank` (`number`, `name`) VALUES (116,'116 - BANCO B.N.L DO BRASIL S.A.')");
        await queryRunner.query("INSERT INTO `bank` (`number`, `name`) VALUES (140,'140 - NU INVEST CORRETORA DE VALORES S.A.')");
        await queryRunner.query("INSERT INTO `bank` (`number`, `name`) VALUES (148,'148 - MULTI BANCO S.A.')");
        await queryRunner.query("INSERT INTO `bank` (`number`, `name`) VALUES (151,'151 - CAIXA ECONOMICA DO ESTADO DE SAO PAULO')");
        await queryRunner.query("INSERT INTO `bank` (`number`, `name`) VALUES (153,'153 - CAIXA ECONOMICA DO ESTADO DO R.G.SUL')");
        await queryRunner.query("INSERT INTO `bank` (`number`, `name`) VALUES (165,'165 - BANCO NORCHEM S.A.')");
        await queryRunner.query("INSERT INTO `bank` (`number`, `name`) VALUES (166,'166 - BANCO INTER-ATLANTICO S.A.')");
        await queryRunner.query("INSERT INTO `bank` (`number`, `name`) VALUES (168,'168 - BANCO C.C.F. BRASIL S.A.')");
        await queryRunner.query("INSERT INTO `bank` (`number`, `name`) VALUES (175,'175 - CONTINENTAL BANCO S.A.')");
        await queryRunner.query("INSERT INTO `bank` (`number`, `name`) VALUES (184,'184 - BBA - CREDITANSTALT S.A.')");
        await queryRunner.query("INSERT INTO `bank` (`number`, `name`) VALUES (199,'199 - BANCO FINANCIAL PORTUGUES')");
        await queryRunner.query("INSERT INTO `bank` (`number`, `name`) VALUES (200,'200 - BANCO FRICRISA AXELRUD S.A.')");
        await queryRunner.query("INSERT INTO `bank` (`number`, `name`) VALUES (201,'201 - BANCO AUGUSTA INDUSTRIA E COMERCIAL S.A.')");
        await queryRunner.query("INSERT INTO `bank` (`number`, `name`) VALUES (204,'204 - BANCO S.R.L S.A.')");
        await queryRunner.query("INSERT INTO `bank` (`number`, `name`) VALUES (205,'205 - BANCO SUL AMERICA S.A.')");
        await queryRunner.query("INSERT INTO `bank` (`number`, `name`) VALUES (206,'206 - BANCO MARTINELLI S.A.')");
        await queryRunner.query("INSERT INTO `bank` (`number`, `name`) VALUES (208,'208 - BANCO PACTUAL S.A.')");
        await queryRunner.query("INSERT INTO `bank` (`number`, `name`) VALUES (210,'210 - DEUTSCH SUDAMERIKANICHE BANK AG')");
        await queryRunner.query("INSERT INTO `bank` (`number`, `name`) VALUES (211,'211 - BANCO SISTEMA S.A.')");
        await queryRunner.query("INSERT INTO `bank` (`number`, `name`) VALUES (212,'212 - BANCO MATONE S.A.')");
        await queryRunner.query("INSERT INTO `bank` (`number`, `name`) VALUES (213,'213 - BANCO ARBI S.A.')");
        await queryRunner.query("INSERT INTO `bank` (`number`, `name`) VALUES (214,'214 - BANCO DIBENS S.A.')");
        await queryRunner.query("INSERT INTO `bank` (`number`, `name`) VALUES (215,'215 - BANCO AMERICA DO SUL S.A.')");
        await queryRunner.query("INSERT INTO `bank` (`number`, `name`) VALUES (216,'216 - BANCO REGIONAL MALCON S.A.')");
        await queryRunner.query("INSERT INTO `bank` (`number`, `name`) VALUES (217,'217 - BANCO AGROINVEST S.A.')");
        await queryRunner.query("INSERT INTO `bank` (`number`, `name`) VALUES (218,'218 - BBS - BANCO BONSUCESSO S.A.')");
        await queryRunner.query("INSERT INTO `bank` (`number`, `name`) VALUES (219,'219 - BANCO DE CREDITO DE SAO PAULO S.A.')");
        await queryRunner.query("INSERT INTO `bank` (`number`, `name`) VALUES (220,'220 - BANCO CREFISUL')");
        await queryRunner.query("INSERT INTO `bank` (`number`, `name`) VALUES (221,'221 - BANCO GRAPHUS S.A.')");
        await queryRunner.query("INSERT INTO `bank` (`number`, `name`) VALUES (222,'222 - BANCO AGF BRASIL S. A.')");
        await queryRunner.query("INSERT INTO `bank` (`number`, `name`) VALUES (223,'223 - BANCO INTERUNION S.A.')");
        await queryRunner.query("INSERT INTO `bank` (`number`, `name`) VALUES (224,'224 - BANCO FIBRA S.A.')");
        await queryRunner.query("INSERT INTO `bank` (`number`, `name`) VALUES (225,'225 - BANCO BRASCAN S.A.')");
        await queryRunner.query("INSERT INTO `bank` (`number`, `name`) VALUES (228,'228 - BANCO ICATU S.A.')");
        await queryRunner.query("INSERT INTO `bank` (`number`, `name`) VALUES (229,'229 - BANCO CRUZEIRO S.A.')");
        await queryRunner.query("INSERT INTO `bank` (`number`, `name`) VALUES (230,'230 - BANCO BANDEIRANTES S.A.')");
        await queryRunner.query("INSERT INTO `bank` (`number`, `name`) VALUES (231,'231 - BANCO BOAVISTA S.A.')");
        await queryRunner.query("INSERT INTO `bank` (`number`, `name`) VALUES (232,'232 - BANCO INTERPART S.A.')");
        await queryRunner.query("INSERT INTO `bank` (`number`, `name`) VALUES (233,'233 - BANCO MAPPIN S.A.')");
        await queryRunner.query("INSERT INTO `bank` (`number`, `name`) VALUES (234,'234 - BANCO LAVRA S.A.')");
        await queryRunner.query("INSERT INTO `bank` (`number`, `name`) VALUES (235,'235 - BANCO LIBERAL S.A.')");
        await queryRunner.query("INSERT INTO `bank` (`number`, `name`) VALUES (236,'236 - BANCO CAMBIAL S.A.')");
        await queryRunner.query("INSERT INTO `bank` (`number`, `name`) VALUES (237,'237 - BANCO BRADESCO S.A.')");
        await queryRunner.query("INSERT INTO `bank` (`number`, `name`) VALUES (239,'239 - BANCO BANCRED S.A.')");
        await queryRunner.query("INSERT INTO `bank` (`number`, `name`) VALUES (240,'240 - BANCO DE CREDITO REAL DE MINAS GERAIS S.')");
        await queryRunner.query("INSERT INTO `bank` (`number`, `name`) VALUES (241,'241 - BANCO CLASSICO S.A.')");
        await queryRunner.query("INSERT INTO `bank` (`number`, `name`) VALUES (242,'242 - BANCO EUROINVEST S.A.')");
        await queryRunner.query("INSERT INTO `bank` (`number`, `name`) VALUES (243,'243 - BANCO STOCK S.A.')");
        await queryRunner.query("INSERT INTO `bank` (`number`, `name`) VALUES (244,'244 - BANCO CIDADE S.A.')");
        await queryRunner.query("INSERT INTO `bank` (`number`, `name`) VALUES (245,'245 - BANCO EMPRESARIAL S.A.')");
        await queryRunner.query("INSERT INTO `bank` (`number`, `name`) VALUES (246,'246 - BANCO ABC ROMA S.A.')");
        await queryRunner.query("INSERT INTO `bank` (`number`, `name`) VALUES (247,'247 - BANCO OMEGA S.A.')");
        await queryRunner.query("INSERT INTO `bank` (`number`, `name`) VALUES (249,'249 - BANCO INVESTCRED S.A.')");
        await queryRunner.query("INSERT INTO `bank` (`number`, `name`) VALUES (250,'250 - BANCO SCHAHIN CURY S.A.')");
        await queryRunner.query("INSERT INTO `bank` (`number`, `name`) VALUES (251,'251 - BANCO SAO JORGE S.A.')");
        await queryRunner.query("INSERT INTO `bank` (`number`, `name`) VALUES (252,'252 - BANCO FININVEST S.A.')");
        await queryRunner.query("INSERT INTO `bank` (`number`, `name`) VALUES (254,'254 - BANCO PARANA BANCO S.A.')");
        await queryRunner.query("INSERT INTO `bank` (`number`, `name`) VALUES (255,'255 - MILBANCO S.A.')");
        await queryRunner.query("INSERT INTO `bank` (`number`, `name`) VALUES (256,'256 - BANCO GULVINVEST S.A.')");
        await queryRunner.query("INSERT INTO `bank` (`number`, `name`) VALUES (258,'258 - BANCO INDUSCRED S.A.')");
        await queryRunner.query("INSERT INTO `bank` (`number`, `name`) VALUES (260,'260 - NU PAGAMENTOS S.A. - INSTITUIÇÃO DE PAGAMENTO')");
        await queryRunner.query("INSERT INTO `bank` (`number`, `name`) VALUES (261,'261 - BANCO VARIG S.A.')");
        await queryRunner.query("INSERT INTO `bank` (`number`, `name`) VALUES (262,'262 - BANCO BOREAL S.A.')");
        await queryRunner.query("INSERT INTO `bank` (`number`, `name`) VALUES (263,'263 - BANCO CACIQUE')");
        await queryRunner.query("INSERT INTO `bank` (`number`, `name`) VALUES (264,'264 - BANCO PERFORMANCE S.A.')");
        await queryRunner.query("INSERT INTO `bank` (`number`, `name`) VALUES (265,'265 - BANCO FATOR S.A.')");
        await queryRunner.query("INSERT INTO `bank` (`number`, `name`) VALUES (266,'266 - BANCO CEDULA S.A.')");
        await queryRunner.query("INSERT INTO `bank` (`number`, `name`) VALUES (267,'267 - BANCO BBM-COM.C.IMOB.CFI S.A.')");
        await queryRunner.query("INSERT INTO `bank` (`number`, `name`) VALUES (275,'275 - BANCO REAL S.A.')");
        await queryRunner.query("INSERT INTO `bank` (`number`, `name`) VALUES (277,'277 - BANCO PLANIBANC S.A.')");
        await queryRunner.query("INSERT INTO `bank` (`number`, `name`) VALUES (282,'282 - BANCO BRASILEIRO COMERCIAL')");
        await queryRunner.query("INSERT INTO `bank` (`number`, `name`) VALUES (291,'291 - BANCO DE CREDITO NACIONAL S.A.')");
        await queryRunner.query("INSERT INTO `bank` (`number`, `name`) VALUES (294,'294 - BCR - BANCO DE CREDITO REAL S.A.')");
        await queryRunner.query("INSERT INTO `bank` (`number`, `name`) VALUES (295,'295 - BANCO CREDIPLAN S.A.')");
        await queryRunner.query("INSERT INTO `bank` (`number`, `name`) VALUES (300,'300 - BANCO DE LA NACION ARGENTINA S.A.')");
        await queryRunner.query("INSERT INTO `bank` (`number`, `name`) VALUES (302,'302 - BANCO DO PROGRESSO S.A.')");
        await queryRunner.query("INSERT INTO `bank` (`number`, `name`) VALUES (303,'303 - BANCO HNF S.A.')");
        await queryRunner.query("INSERT INTO `bank` (`number`, `name`) VALUES (304,'304 - BANCO PONTUAL S.A.')");
        await queryRunner.query("INSERT INTO `bank` (`number`, `name`) VALUES (308,'308 - BANCO COMERCIAL BANCESA S.A.')");
        await queryRunner.query("INSERT INTO `bank` (`number`, `name`) VALUES (318,'318 - BANCO B.M.G. S.A.')");
        await queryRunner.query("INSERT INTO `bank` (`number`, `name`) VALUES (320,'320 - BANCO INDUSTRIAL E COMERCIAL')");
        await queryRunner.query("INSERT INTO `bank` (`number`, `name`) VALUES (336,'336 - BANCO C6 S.A.')");
        await queryRunner.query("INSERT INTO `bank` (`number`, `name`) VALUES (341,'341 - BANCO ITAU S.A.')");
        await queryRunner.query("INSERT INTO `bank` (`number`, `name`) VALUES (346,'346 - BANCO FRANCES E BRASILEIRO S.A.')");
        await queryRunner.query("INSERT INTO `bank` (`number`, `name`) VALUES (347,'347 - BANCO SUDAMERIS BRASIL S.A.')");
        await queryRunner.query("INSERT INTO `bank` (`number`, `name`) VALUES (348,'348 - BANCO XP S.A.')");
        await queryRunner.query("INSERT INTO `bank` (`number`, `name`) VALUES (351,'351 - BANCO BOZANO SIMONSEN S.A.')");
        await queryRunner.query("INSERT INTO `bank` (`number`, `name`) VALUES (353,'353 - BANCO GERAL DO COMERCIO S.A.')");
        await queryRunner.query("INSERT INTO `bank` (`number`, `name`) VALUES (356,'356 - ABN AMRO S.A.')");
        await queryRunner.query("INSERT INTO `bank` (`number`, `name`) VALUES (366,'366 - BANCO SOGERAL S.A.')");
        await queryRunner.query("INSERT INTO `bank` (`number`, `name`) VALUES (369,'369 - PONTUAL')");
        await queryRunner.query("INSERT INTO `bank` (`number`, `name`) VALUES (370,'370 - BEAL - BANCO EUROPEU PARA AMERICA LATINA')");
        await queryRunner.query("INSERT INTO `bank` (`number`, `name`) VALUES (372,'372 - BANCO ITAMARATI S.A.')");
        await queryRunner.query("INSERT INTO `bank` (`number`, `name`) VALUES (375,'375 - BANCO FENICIA S.A.')");
        await queryRunner.query("INSERT INTO `bank` (`number`, `name`) VALUES (376,'376 - CHASE MANHATTAN BANK S.A.')");
        await queryRunner.query("INSERT INTO `bank` (`number`, `name`) VALUES (386,'386 - NU FINANCEIRA S.A. - Sociedade de Crédito, Financiamento e Investimento')");
        await queryRunner.query("INSERT INTO `bank` (`number`, `name`) VALUES (388,'388 - BANCO MERCANTIL DE DESCONTOS S/A')");
        await queryRunner.query("INSERT INTO `bank` (`number`, `name`) VALUES (389,'389 - BANCO MERCANTIL DO BRASIL S.A.')");
        await queryRunner.query("INSERT INTO `bank` (`number`, `name`) VALUES (392,'392 - BANCO MERCANTIL DE SAO PAULO S.A.')");
        await queryRunner.query("INSERT INTO `bank` (`number`, `name`) VALUES (394,'394 - BANCO B.M.C. S.A.')");
        await queryRunner.query("INSERT INTO `bank` (`number`, `name`) VALUES (399,'399 - BANCO BAMERINDUS DO BRASIL S.A.')");
        await queryRunner.query("INSERT INTO `bank` (`number`, `name`) VALUES (409,'409 - UNIBANCO - UNIAO DOS BANCOS BRASILEIROS')");
        await queryRunner.query("INSERT INTO `bank` (`number`, `name`) VALUES (412,'412 - BANCO NACIONAL DA BAHIA S.A.')");
        await queryRunner.query("INSERT INTO `bank` (`number`, `name`) VALUES (415,'415 - BANCO NACIONAL S.A.')");
        await queryRunner.query("INSERT INTO `bank` (`number`, `name`) VALUES (420,'420 - BANCO NACIONAL DO NORTE S.A.')");
        await queryRunner.query("INSERT INTO `bank` (`number`, `name`) VALUES (422,'422 - BANCO SAFRA S.A.')");
        await queryRunner.query("INSERT INTO `bank` (`number`, `name`) VALUES (424,'424 - BANCO NOROESTE S.A.')");
        await queryRunner.query("INSERT INTO `bank` (`number`, `name`) VALUES (434,'434 - BANCO FORTALEZA S.A.')");
        await queryRunner.query("INSERT INTO `bank` (`number`, `name`) VALUES (453,'453 - BANCO RURAL S.A.')");
        await queryRunner.query("INSERT INTO `bank` (`number`, `name`) VALUES (456,'456 - BANCO TOKIO S.A.')");
        await queryRunner.query("INSERT INTO `bank` (`number`, `name`) VALUES (464,'464 - BANCO SUMITOMO BRASILEIRO S.A.')");
        await queryRunner.query("INSERT INTO `bank` (`number`, `name`) VALUES (466,'466 - BANCO MITSUBISHI BRASILEIRO S.A.')");
        await queryRunner.query("INSERT INTO `bank` (`number`, `name`) VALUES (472,'472 - LLOYDS BANK PLC')");
        await queryRunner.query("INSERT INTO `bank` (`number`, `name`) VALUES (473,'473 - BANCO FINANCIAL PORTUGUES S.A.')");
        await queryRunner.query("INSERT INTO `bank` (`number`, `name`) VALUES (477,'477 - CITIBANK N.A.')");
        await queryRunner.query("INSERT INTO `bank` (`number`, `name`) VALUES (479,'479 - BANCO DE BOSTON S.A.')");
        await queryRunner.query("INSERT INTO `bank` (`number`, `name`) VALUES (480,'480 - BANCO PORTUGUES DO ATLANTICO-BRASIL S.A.')");
        await queryRunner.query("INSERT INTO `bank` (`number`, `name`) VALUES (483,'483 - BANCO AGRIMISA S.A.')");
        await queryRunner.query("INSERT INTO `bank` (`number`, `name`) VALUES (487,'487 - DEUTSCHE BANK S.A - BANCO ALEMAO')");
        await queryRunner.query("INSERT INTO `bank` (`number`, `name`) VALUES (488,'488 - BANCO J. P. MORGAN S.A.')");
        await queryRunner.query("INSERT INTO `bank` (`number`, `name`) VALUES (489,'489 - BANESTO BANCO URUGAUAY S.A.')");
        await queryRunner.query("INSERT INTO `bank` (`number`, `name`) VALUES (492,'492 - INTERNATIONALE NEDERLANDEN BANK N.V.')");
        await queryRunner.query("INSERT INTO `bank` (`number`, `name`) VALUES (493,'493 - BANCO UNION S.A.C.A.')");
        await queryRunner.query("INSERT INTO `bank` (`number`, `name`) VALUES (494,'494 - BANCO LA REP. ORIENTAL DEL URUGUAY')");
        await queryRunner.query("INSERT INTO `bank` (`number`, `name`) VALUES (495,'495 - BANCO LA PROVINCIA DE BUENOS AIRES')");
        await queryRunner.query("INSERT INTO `bank` (`number`, `name`) VALUES (496,'496 - BANCO EXTERIOR DE ESPANA S.A.')");
        await queryRunner.query("INSERT INTO `bank` (`number`, `name`) VALUES (498,'498 - CENTRO HISPANO BANCO')");
        await queryRunner.query("INSERT INTO `bank` (`number`, `name`) VALUES (499,'499 - BANCO IOCHPE S.A.')");
        await queryRunner.query("INSERT INTO `bank` (`number`, `name`) VALUES (501,'501 - BANCO BRASILEIRO IRAQUIANO S.A.')");
        await queryRunner.query("INSERT INTO `bank` (`number`, `name`) VALUES (502,'502 - BANCO SANTANDER S.A.')");
        await queryRunner.query("INSERT INTO `bank` (`number`, `name`) VALUES (504,'504 - BANCO MULTIPLIC S.A.')");
        await queryRunner.query("INSERT INTO `bank` (`number`, `name`) VALUES (505,'505 - BANCO GARANTIA S.A.')");
        await queryRunner.query("INSERT INTO `bank` (`number`, `name`) VALUES (600,'600 - BANCO LUSO BRASILEIRO S.A.')");
        await queryRunner.query("INSERT INTO `bank` (`number`, `name`) VALUES (601,'601 - BFC BANCO S.A.')");
        await queryRunner.query("INSERT INTO `bank` (`number`, `name`) VALUES (602,'602 - BANCO PATENTE S.A.')");
        await queryRunner.query("INSERT INTO `bank` (`number`, `name`) VALUES (604,'604 - BANCO INDUSTRIAL DO BRASIL S.A.')");
        await queryRunner.query("INSERT INTO `bank` (`number`, `name`) VALUES (607,'607 - BANCO SANTOS NEVES S.A.')");
        await queryRunner.query("INSERT INTO `bank` (`number`, `name`) VALUES (608,'608 - BANCO OPEN S.A.')");
        await queryRunner.query("INSERT INTO `bank` (`number`, `name`) VALUES (610,'610 - BANCO V.R. S.A.')");
        await queryRunner.query("INSERT INTO `bank` (`number`, `name`) VALUES (611,'611 - BANCO PAULISTA S.A.')");
        await queryRunner.query("INSERT INTO `bank` (`number`, `name`) VALUES (612,'612 - BANCO GUANABARA S.A.')");
        await queryRunner.query("INSERT INTO `bank` (`number`, `name`) VALUES (613,'613 - OMNI BANCO S.A.')");
        await queryRunner.query("INSERT INTO `bank` (`number`, `name`) VALUES (616,'616 - BANCO INTERPACIFICO S.A.')");
        await queryRunner.query("INSERT INTO `bank` (`number`, `name`) VALUES (617,'617 - BANCO INVESTOR S.A.')");
        await queryRunner.query("INSERT INTO `bank` (`number`, `name`) VALUES (618,'618 - BANCO TENDENCIA S.A.')");
        await queryRunner.query("INSERT INTO `bank` (`number`, `name`) VALUES (621,'621 - BANCO APLICAP S.A.')");
        await queryRunner.query("INSERT INTO `bank` (`number`, `name`) VALUES (622,'622 - BANCO DRACMA S.A.')");
        await queryRunner.query("INSERT INTO `bank` (`number`, `name`) VALUES (623,'623 - BANCO PAN S.A.')");
        await queryRunner.query("INSERT INTO `bank` (`number`, `name`) VALUES (624,'624 - BANCO GENERAL MOTORS S.A.')");
        await queryRunner.query("INSERT INTO `bank` (`number`, `name`) VALUES (625,'625 - BANCO ARAUCARIA S.A.')");
        await queryRunner.query("INSERT INTO `bank` (`number`, `name`) VALUES (626,'626 - BANCO C6 CONSIGNADO S.A.')");
        await queryRunner.query("INSERT INTO `bank` (`number`, `name`) VALUES (627,'627 - BANCO DESTAK S.A.')");
        await queryRunner.query("INSERT INTO `bank` (`number`, `name`) VALUES (628,'628 - BANCO CRITERIUM S.A.')");
        await queryRunner.query("INSERT INTO `bank` (`number`, `name`) VALUES (629,'629 - BANCORP BANCO COML. E. DE INVESTMENTO')");
        await queryRunner.query("INSERT INTO `bank` (`number`, `name`) VALUES (630,'630 - BANCO INTERCAP S.A.')");
        await queryRunner.query("INSERT INTO `bank` (`number`, `name`) VALUES (633,'633 - BANCO REDIMENTO S.A.')");
        await queryRunner.query("INSERT INTO `bank` (`number`, `name`) VALUES (634,'634 - BANCO TRIANGULO S.A.')");
        await queryRunner.query("INSERT INTO `bank` (`number`, `name`) VALUES (635,'635 - BANCO DO ESTADO DO AMAPA S.A.')");
        await queryRunner.query("INSERT INTO `bank` (`number`, `name`) VALUES (637,'637 - BANCO SOFISA S.A.')");
        await queryRunner.query("INSERT INTO `bank` (`number`, `name`) VALUES (638,'638 - BANCO PROSPER S.A.')");
        await queryRunner.query("INSERT INTO `bank` (`number`, `name`) VALUES (639,'639 - BIG S.A. - BANCO IRMAOS GUIMARAES')");
        await queryRunner.query("INSERT INTO `bank` (`number`, `name`) VALUES (640,'640 - BANCO DE CREDITO METROPOLITANO S.A.')");
        await queryRunner.query("INSERT INTO `bank` (`number`, `name`) VALUES (641,'641 - BANCO EXCEL ECONOMICO S/A')");
        await queryRunner.query("INSERT INTO `bank` (`number`, `name`) VALUES (643,'643 - BANCO SEGMENTO S.A.')");
        await queryRunner.query("INSERT INTO `bank` (`number`, `name`) VALUES (645,'645 - BANCO DO ESTADO DE RORAIMA S.A.')");
        await queryRunner.query("INSERT INTO `bank` (`number`, `name`) VALUES (647,'647 - BANCO MARKA S.A.')");
        await queryRunner.query("INSERT INTO `bank` (`number`, `name`) VALUES (648,'648 - BANCO ATLANTIS S.A.')");
        await queryRunner.query("INSERT INTO `bank` (`number`, `name`) VALUES (649,'649 - BANCO DIMENSAO S.A.')");
        await queryRunner.query("INSERT INTO `bank` (`number`, `name`) VALUES (650,'650 - BANCO PEBB S.A.')");
        await queryRunner.query("INSERT INTO `bank` (`number`, `name`) VALUES (652,'652 - BANCO FRANCES E BRASILEIRO SA')");
        await queryRunner.query("INSERT INTO `bank` (`number`, `name`) VALUES (653,'653 - BANCO INDUSVAL S.A.')");
        await queryRunner.query("INSERT INTO `bank` (`number`, `name`) VALUES (654,'654 - BANCO A. J. RENNER S.A.')");
        await queryRunner.query("INSERT INTO `bank` (`number`, `name`) VALUES (655,'655 - BANCO VOTORANTIM S.A.')");
        await queryRunner.query("INSERT INTO `bank` (`number`, `name`) VALUES (656,'656 - BANCO MATRIX S.A.')");
        await queryRunner.query("INSERT INTO `bank` (`number`, `name`) VALUES (657,'657 - BANCO TECNICORP S.A.')");
        await queryRunner.query("INSERT INTO `bank` (`number`, `name`) VALUES (658,'658 - BANCO PORTO REAL S.A.')");
        await queryRunner.query("INSERT INTO `bank` (`number`, `name`) VALUES (702,'702 - BANCO SANTOS S.A.')");
        await queryRunner.query("INSERT INTO `bank` (`number`, `name`) VALUES (705,'705 - BANCO INVESTCORP S.A.')");
        await queryRunner.query("INSERT INTO `bank` (`number`, `name`) VALUES (707,'707 - BANCO DAYCOVAL S.A.')");
        await queryRunner.query("INSERT INTO `bank` (`number`, `name`) VALUES (711,'711 - BANCO VETOR S.A.')");
        await queryRunner.query("INSERT INTO `bank` (`number`, `name`) VALUES (713,'713 - BANCO CINDAM S.A.')");
        await queryRunner.query("INSERT INTO `bank` (`number`, `name`) VALUES (715,'715 - BANCO VEGA S.A.')");
        await queryRunner.query("INSERT INTO `bank` (`number`, `name`) VALUES (718,'718 - BANCO OPERADOR S.A.')");
        await queryRunner.query("INSERT INTO `bank` (`number`, `name`) VALUES (719,'719 - BANCO PRIMUS S.A.')");
        await queryRunner.query("INSERT INTO `bank` (`number`, `name`) VALUES (720,'720 - BANCO MAXINVEST S.A.')");
        await queryRunner.query("INSERT INTO `bank` (`number`, `name`) VALUES (721,'721 - BANCO CREDIBEL S.A.')");
        await queryRunner.query("INSERT INTO `bank` (`number`, `name`) VALUES (722,'722 - BANCO INTERIOR DE SAO PAULO S.A.')");
        await queryRunner.query("INSERT INTO `bank` (`number`, `name`) VALUES (724,'724 - BANCO PORTO SEGURO S.A.')");
        await queryRunner.query("INSERT INTO `bank` (`number`, `name`) VALUES (725,'725 - BANCO FINABANCO S.A.')");
        await queryRunner.query("INSERT INTO `bank` (`number`, `name`) VALUES (726,'726 - BANCO UNIVERSAL S.A.')");
        await queryRunner.query("INSERT INTO `bank` (`number`, `name`) VALUES (728,'728 - BANCO FITAL S.A.')");
        await queryRunner.query("INSERT INTO `bank` (`number`, `name`) VALUES (729,'729 - BANCO FONTE S.A.')");
        await queryRunner.query("INSERT INTO `bank` (`number`, `name`) VALUES (730,'730 - BANCO COMERCIAL PARAGUAYO S.A.')");
        await queryRunner.query("INSERT INTO `bank` (`number`, `name`) VALUES (731,'731 - BANCO GNPP S.A.')");
        await queryRunner.query("INSERT INTO `bank` (`number`, `name`) VALUES (732,'732 - BANCO PREMIER S.A.')");
        await queryRunner.query("INSERT INTO `bank` (`number`, `name`) VALUES (733,'733 - BANCO NACOES S.A.')");
        await queryRunner.query("INSERT INTO `bank` (`number`, `name`) VALUES (734,'734 - BANCO GERDAU S.A.')");
        await queryRunner.query("INSERT INTO `bank` (`number`, `name`) VALUES (735,'735 - BACO POTENCIAL')");
        await queryRunner.query("INSERT INTO `bank` (`number`, `name`) VALUES (736,'736 - BANCO UNITED S.A.')");
        await queryRunner.query("INSERT INTO `bank` (`number`, `name`) VALUES (737,'737 - THECA')");
        await queryRunner.query("INSERT INTO `bank` (`number`, `name`) VALUES (738,'738 - MARADA')");
        await queryRunner.query("INSERT INTO `bank` (`number`, `name`) VALUES (739,'739 - BGN')");
        await queryRunner.query("INSERT INTO `bank` (`number`, `name`) VALUES (740,'740 - BCN BARCLAYS')");
        await queryRunner.query("INSERT INTO `bank` (`number`, `name`) VALUES (741,'741 - BRP')");
        await queryRunner.query("INSERT INTO `bank` (`number`, `name`) VALUES (742,'742 - EQUATORIAL')");
        await queryRunner.query("INSERT INTO `bank` (`number`, `name`) VALUES (743,'743 - BANCO EMBLEMA S.A.')");
        await queryRunner.query("INSERT INTO `bank` (`number`, `name`) VALUES (744,'744 - THE FIRST NATIONAL BANK OF BOSTON')");
        await queryRunner.query("INSERT INTO `bank` (`number`, `name`) VALUES (745,'745 - CITIBAN N.A.')");
        await queryRunner.query("INSERT INTO `bank` (`number`, `name`) VALUES (746,'746 - MODAL S\A')");
        await queryRunner.query("INSERT INTO `bank` (`number`, `name`) VALUES (747,'747 - RAIBOBANK DO BRASIL')");
        await queryRunner.query("INSERT INTO `bank` (`number`, `name`) VALUES (748,'748 - SICREDI')");
        await queryRunner.query("INSERT INTO `bank` (`number`, `name`) VALUES (749,'749 - BRMSANTIL SA')");
        await queryRunner.query("INSERT INTO `bank` (`number`, `name`) VALUES (750,'750 - BANCO REPUBLIC NATIONAL OF NEW YORK (BRA')");
        await queryRunner.query("INSERT INTO `bank` (`number`, `name`) VALUES (751,'751 - DRESDNER BANK LATEINAMERIKA-BRASIL S/A')");
        await queryRunner.query("INSERT INTO `bank` (`number`, `name`) VALUES (752,'752 - BANCO BANQUE NATIONALE DE PARIS BRASIL S')");
        await queryRunner.query("INSERT INTO `bank` (`number`, `name`) VALUES (753,'753 - BANCO COMERCIAL URUGUAI S.A.')");
        await queryRunner.query("INSERT INTO `bank` (`number`, `name`) VALUES (755,'755 - BANCO MERRILL LYNCH S.A.')");
        await queryRunner.query("INSERT INTO `bank` (`number`, `name`) VALUES (756,'756 - BANCO COOPERATIVO DO BRASIL S.A.')");
        await queryRunner.query("INSERT INTO `bank` (`number`, `name`) VALUES (757,'757 - BANCO KEB DO BRASIL S.A.')");
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query("DELETE FROM `bank` WHERE number = 001 AND name = '001 - BANCO DO BRASIL S/A'");
        await queryRunner.query("DELETE FROM `bank` WHERE number = 002 AND name = '002 - BANCO CENTRAL DO BRASIL'");
        await queryRunner.query("DELETE FROM `bank` WHERE number = 003 AND name = '003 - BANCO DA AMAZONIA S.A.'");
        await queryRunner.query("DELETE FROM `bank` WHERE number = 004 AND name = '004 - BANCO DO NORDESTE DO BRASIL S.A.'");
        await queryRunner.query("DELETE FROM `bank` WHERE number = 007 AND name = '007 - BANCO NAC DESENV. ECO. SOCIAL S.A.'");
        await queryRunner.query("DELETE FROM `bank` WHERE number = 008 AND name = '008 - BANCO MERIDIONAL DO BRASIL'");
        await queryRunner.query("DELETE FROM `bank` WHERE number = 020 AND name = '020 - BANCO DO ESTADO DE ALAGOAS S.A.'");
        await queryRunner.query("DELETE FROM `bank` WHERE number = 021 AND name = '021 - BANCO DO ESTADO DO ESPIRITO SANTO S.A.'");
        await queryRunner.query("DELETE FROM `bank` WHERE number = 022 AND name = '022 - BANCO DE CREDITO REAL DE MINAS GERAIS SA'");
        await queryRunner.query("DELETE FROM `bank` WHERE number = 024 AND name = '024 - BANCO DO ESTADO DE PERNAMBUCO'");
        await queryRunner.query("DELETE FROM `bank` WHERE number = 025 AND name = '025 - BANCO ALFA S/A'");
        await queryRunner.query("DELETE FROM `bank` WHERE number = 026 AND name = '026 - BANCO DO ESTADO DO ACRE S.A.'");
        await queryRunner.query("DELETE FROM `bank` WHERE number = 027 AND name = '027 - BANCO DO ESTADO DE SANTA CATARINA S.A.'");
        await queryRunner.query("DELETE FROM `bank` WHERE number = 028 AND name = '028 - BANCO DO ESTADO DA BAHIA S.A.'");
        await queryRunner.query("DELETE FROM `bank` WHERE number = 029 AND name = '029 - BANCO DO ESTADO DO RIO DE JANEIRO S.A.'");
        await queryRunner.query("DELETE FROM `bank` WHERE number = 030 AND name = '030 - BANCO DO ESTADO DA PARAIBA S.A.'");
        await queryRunner.query("DELETE FROM `bank` WHERE number = 031 AND name = '031 - BANCO DO ESTADO DE GOIAS S.A.'");
        await queryRunner.query("DELETE FROM `bank` WHERE number = 032 AND name = '032 - BANCO DO ESTADO DO MATO GROSSO S.A.'");
        await queryRunner.query("DELETE FROM `bank` WHERE number = 033 AND name = '033 - BANCO DO ESTADO DE SAO PAULO S.A.'");
        await queryRunner.query("DELETE FROM `bank` WHERE number = 034 AND name = '034 - BANCO DO ESADO DO AMAZONAS S.A.'");
        await queryRunner.query("DELETE FROM `bank` WHERE number = 035 AND name = '035 - BANCO DO ESTADO DO CEARA S.A.'");
        await queryRunner.query("DELETE FROM `bank` WHERE number = 036 AND name = '036 - BANCO DO ESTADO DO MARANHAO S.A.'");
        await queryRunner.query("DELETE FROM `bank` WHERE number = 037 AND name = '037 - BANCO DO ESTADO DO PARA S.A.'");
        await queryRunner.query("DELETE FROM `bank` WHERE number = 038 AND name = '038 - BANCO DO ESTADO DO PARANA S.A.'");
        await queryRunner.query("DELETE FROM `bank` WHERE number = 039 AND name = '039 - BANCO DO ESTADO DO PIAUI S.A.'");
        await queryRunner.query("DELETE FROM `bank` WHERE number = 041 AND name = '041 - BANCO DO ESTADO DO RIO GRANDE DO SUL S.A.'");
        await queryRunner.query("DELETE FROM `bank` WHERE number = 047 AND name = '047 - BANCO DO ESTADO DE SERGIPE S.A.'");
        await queryRunner.query("DELETE FROM `bank` WHERE number = 048 AND name = '048 - BANCO DO ESTADO DE MINAS GERAIS S.A.'");
        await queryRunner.query("DELETE FROM `bank` WHERE number = 059 AND name = '059 - BANCO DO ESTADO DE RONDONIA S.A.'");
        await queryRunner.query("DELETE FROM `bank` WHERE number = 070 AND name = '070 - BANCO DE BRASILIA S.A.'");
        await queryRunner.query("DELETE FROM `bank` WHERE number = 077 AND name = '077 - BANCO INTER S.A.'");
        await queryRunner.query("DELETE FROM `bank` WHERE number = 104 AND name = '104 - CAIXA ECONOMICA FEDERAL'");
        await queryRunner.query("DELETE FROM `bank` WHERE number = 106 AND name = '106 - BANCO ITABANCO S.A.'");
        await queryRunner.query("DELETE FROM `bank` WHERE number = 107 AND name = '107 - BANCO BBM S.A.'");
        await queryRunner.query("DELETE FROM `bank` WHERE number = 109 AND name = '109 - BANCO CREDIBANCO S.A.'");
        await queryRunner.query("DELETE FROM `bank` WHERE number = 116 AND name = '116 - BANCO B.N.L DO BRASIL S.A.'");
        await queryRunner.query("DELETE FROM `bank` WHERE number = 140 AND name = '140 - NU INVEST CORRETORA DE VALORES S.A.'");
        await queryRunner.query("DELETE FROM `bank` WHERE number = 148 AND name = '148 - MULTI BANCO S.A.'");
        await queryRunner.query("DELETE FROM `bank` WHERE number = 151 AND name = '151 - CAIXA ECONOMICA DO ESTADO DE SAO PAULO'");
        await queryRunner.query("DELETE FROM `bank` WHERE number = 153 AND name = '153 - CAIXA ECONOMICA DO ESTADO DO R.G.SUL'");
        await queryRunner.query("DELETE FROM `bank` WHERE number = 165 AND name = '165 - BANCO NORCHEM S.A.'");
        await queryRunner.query("DELETE FROM `bank` WHERE number = 166 AND name = '166 - BANCO INTER-ATLANTICO S.A.'");
        await queryRunner.query("DELETE FROM `bank` WHERE number = 168 AND name = '168 - BANCO C.C.F. BRASIL S.A.'");
        await queryRunner.query("DELETE FROM `bank` WHERE number = 175 AND name = '175 - CONTINENTAL BANCO S.A.'");
        await queryRunner.query("DELETE FROM `bank` WHERE number = 184 AND name = '184 - BBA - CREDITANSTALT S.A.'");
        await queryRunner.query("DELETE FROM `bank` WHERE number = 199 AND name = '199 - BANCO FINANCIAL PORTUGUES'");
        await queryRunner.query("DELETE FROM `bank` WHERE number = 200 AND name = '200 - BANCO FRICRISA AXELRUD S.A.'");
        await queryRunner.query("DELETE FROM `bank` WHERE number = 201 AND name = '201 - BANCO AUGUSTA INDUSTRIA E COMERCIAL S.A.'");
        await queryRunner.query("DELETE FROM `bank` WHERE number = 204 AND name = '204 - BANCO S.R.L S.A.'");
        await queryRunner.query("DELETE FROM `bank` WHERE number = 205 AND name = '205 - BANCO SUL AMERICA S.A.'");
        await queryRunner.query("DELETE FROM `bank` WHERE number = 206 AND name = '206 - BANCO MARTINELLI S.A.'");
        await queryRunner.query("DELETE FROM `bank` WHERE number = 208 AND name = '208 - BANCO PACTUAL S.A.'");
        await queryRunner.query("DELETE FROM `bank` WHERE number = 210 AND name = '210 - DEUTSCH SUDAMERIKANICHE BANK AG'");
        await queryRunner.query("DELETE FROM `bank` WHERE number = 211 AND name = '211 - BANCO SISTEMA S.A.'");
        await queryRunner.query("DELETE FROM `bank` WHERE number = 212 AND name = '212 - BANCO MATONE S.A.'");
        await queryRunner.query("DELETE FROM `bank` WHERE number = 213 AND name = '213 - BANCO ARBI S.A.'");
        await queryRunner.query("DELETE FROM `bank` WHERE number = 214 AND name = '214 - BANCO DIBENS S.A.'");
        await queryRunner.query("DELETE FROM `bank` WHERE number = 215 AND name = '215 - BANCO AMERICA DO SUL S.A.'");
        await queryRunner.query("DELETE FROM `bank` WHERE number = 216 AND name = '216 - BANCO REGIONAL MALCON S.A.'");
        await queryRunner.query("DELETE FROM `bank` WHERE number = 217 AND name = '217 - BANCO AGROINVEST S.A.'");
        await queryRunner.query("DELETE FROM `bank` WHERE number = 218 AND name = '218 - BBS - BANCO BONSUCESSO S.A.'");
        await queryRunner.query("DELETE FROM `bank` WHERE number = 219 AND name = '219 - BANCO DE CREDITO DE SAO PAULO S.A.'");
        await queryRunner.query("DELETE FROM `bank` WHERE number = 220 AND name = '220 - BANCO CREFISUL'");
        await queryRunner.query("DELETE FROM `bank` WHERE number = 221 AND name = '221 - BANCO GRAPHUS S.A.'");
        await queryRunner.query("DELETE FROM `bank` WHERE number = 222 AND name = '222 - BANCO AGF BRASIL S. A.'");
        await queryRunner.query("DELETE FROM `bank` WHERE number = 223 AND name = '223 - BANCO INTERUNION S.A.'");
        await queryRunner.query("DELETE FROM `bank` WHERE number = 224 AND name = '224 - BANCO FIBRA S.A.'");
        await queryRunner.query("DELETE FROM `bank` WHERE number = 225 AND name = '225 - BANCO BRASCAN S.A.'");
        await queryRunner.query("DELETE FROM `bank` WHERE number = 228 AND name = '228 - BANCO ICATU S.A.'");
        await queryRunner.query("DELETE FROM `bank` WHERE number = 229 AND name = '229 - BANCO CRUZEIRO S.A.'");
        await queryRunner.query("DELETE FROM `bank` WHERE number = 230 AND name = '230 - BANCO BANDEIRANTES S.A.'");
        await queryRunner.query("DELETE FROM `bank` WHERE number = 231 AND name = '231 - BANCO BOAVISTA S.A.'");
        await queryRunner.query("DELETE FROM `bank` WHERE number = 232 AND name = '232 - BANCO INTERPART S.A.'");
        await queryRunner.query("DELETE FROM `bank` WHERE number = 233 AND name = '233 - BANCO MAPPIN S.A.'");
        await queryRunner.query("DELETE FROM `bank` WHERE number = 234 AND name = '234 - BANCO LAVRA S.A.'");
        await queryRunner.query("DELETE FROM `bank` WHERE number = 235 AND name = '235 - BANCO LIBERAL S.A.'");
        await queryRunner.query("DELETE FROM `bank` WHERE number = 236 AND name = '236 - BANCO CAMBIAL S.A.'");
        await queryRunner.query("DELETE FROM `bank` WHERE number = 237 AND name = '237 - BANCO BRADESCO S.A.'");
        await queryRunner.query("DELETE FROM `bank` WHERE number = 239 AND name = '239 - BANCO BANCRED S.A.'");
        await queryRunner.query("DELETE FROM `bank` WHERE number = 240 AND name = '240 - BANCO DE CREDITO REAL DE MINAS GERAIS S.'");
        await queryRunner.query("DELETE FROM `bank` WHERE number = 241 AND name = '241 - BANCO CLASSICO S.A.'");
        await queryRunner.query("DELETE FROM `bank` WHERE number = 242 AND name = '242 - BANCO EUROINVEST S.A.'");
        await queryRunner.query("DELETE FROM `bank` WHERE number = 243 AND name = '243 - BANCO STOCK S.A.'");
        await queryRunner.query("DELETE FROM `bank` WHERE number = 244 AND name = '244 - BANCO CIDADE S.A.'");
        await queryRunner.query("DELETE FROM `bank` WHERE number = 245 AND name = '245 - BANCO EMPRESARIAL S.A.'");
        await queryRunner.query("DELETE FROM `bank` WHERE number = 246 AND name = '246 - BANCO ABC ROMA S.A.'");
        await queryRunner.query("DELETE FROM `bank` WHERE number = 247 AND name = '247 - BANCO OMEGA S.A.'");
        await queryRunner.query("DELETE FROM `bank` WHERE number = 249 AND name = '249 - BANCO INVESTCRED S.A.'");
        await queryRunner.query("DELETE FROM `bank` WHERE number = 250 AND name = '250 - BANCO SCHAHIN CURY S.A.'");
        await queryRunner.query("DELETE FROM `bank` WHERE number = 251 AND name = '251 - BANCO SAO JORGE S.A.'");
        await queryRunner.query("DELETE FROM `bank` WHERE number = 252 AND name = '252 - BANCO FININVEST S.A.'");
        await queryRunner.query("DELETE FROM `bank` WHERE number = 254 AND name = '254 - BANCO PARANA BANCO S.A.'");
        await queryRunner.query("DELETE FROM `bank` WHERE number = 255 AND name = '255 - MILBANCO S.A.'");
        await queryRunner.query("DELETE FROM `bank` WHERE number = 256 AND name = '256 - BANCO GULVINVEST S.A.'");
        await queryRunner.query("DELETE FROM `bank` WHERE number = 258 AND name = '258 - BANCO INDUSCRED S.A.'");
        await queryRunner.query("DELETE FROM `bank` WHERE number = 260 AND name = '260 - NU PAGAMENTOS S.A. - INSTITUIÇÃO DE PAGAMENTO'");
        await queryRunner.query("DELETE FROM `bank` WHERE number = 261 AND name = '261 - BANCO VARIG S.A.'");
        await queryRunner.query("DELETE FROM `bank` WHERE number = 262 AND name = '262 - BANCO BOREAL S.A.'");
        await queryRunner.query("DELETE FROM `bank` WHERE number = 263 AND name = '263 - BANCO CACIQUE'");
        await queryRunner.query("DELETE FROM `bank` WHERE number = 264 AND name = '264 - BANCO PERFORMANCE S.A.'");
        await queryRunner.query("DELETE FROM `bank` WHERE number = 265 AND name = '265 - BANCO FATOR S.A.'");
        await queryRunner.query("DELETE FROM `bank` WHERE number = 266 AND name = '266 - BANCO CEDULA S.A.'");
        await queryRunner.query("DELETE FROM `bank` WHERE number = 267 AND name = '267 - BANCO BBM-COM.C.IMOB.CFI S.A.'");
        await queryRunner.query("DELETE FROM `bank` WHERE number = 275 AND name = '275 - BANCO REAL S.A.'");
        await queryRunner.query("DELETE FROM `bank` WHERE number = 277 AND name = '277 - BANCO PLANIBANC S.A.'");
        await queryRunner.query("DELETE FROM `bank` WHERE number = 282 AND name = '282 - BANCO BRASILEIRO COMERCIAL'");
        await queryRunner.query("DELETE FROM `bank` WHERE number = 291 AND name = '291 - BANCO DE CREDITO NACIONAL S.A.'");
        await queryRunner.query("DELETE FROM `bank` WHERE number = 294 AND name = '294 - BCR - BANCO DE CREDITO REAL S.A.'");
        await queryRunner.query("DELETE FROM `bank` WHERE number = 295 AND name = '295 - BANCO CREDIPLAN S.A.'");
        await queryRunner.query("DELETE FROM `bank` WHERE number = 300 AND name = '300 - BANCO DE LA NACION ARGENTINA S.A.'");
        await queryRunner.query("DELETE FROM `bank` WHERE number = 302 AND name = '302 - BANCO DO PROGRESSO S.A.'");
        await queryRunner.query("DELETE FROM `bank` WHERE number = 303 AND name = '303 - BANCO HNF S.A.'");
        await queryRunner.query("DELETE FROM `bank` WHERE number = 304 AND name = '304 - BANCO PONTUAL S.A.'");
        await queryRunner.query("DELETE FROM `bank` WHERE number = 308 AND name = '308 - BANCO COMERCIAL BANCESA S.A.'");
        await queryRunner.query("DELETE FROM `bank` WHERE number = 318 AND name = '318 - BANCO B.M.G. S.A.'");
        await queryRunner.query("DELETE FROM `bank` WHERE number = 320 AND name = '320 - BANCO INDUSTRIAL E COMERCIAL'");
        await queryRunner.query("DELETE FROM `bank` WHERE number = 336 AND name = '336 - BANCO C6 S.A.'");
        await queryRunner.query("DELETE FROM `bank` WHERE number = 341 AND name = '341 - BANCO ITAU S.A.'");
        await queryRunner.query("DELETE FROM `bank` WHERE number = 346 AND name = '346 - BANCO FRANCES E BRASILEIRO S.A.'");
        await queryRunner.query("DELETE FROM `bank` WHERE number = 347 AND name = '347 - BANCO SUDAMERIS BRASIL S.A.'");
        await queryRunner.query("DELETE FROM `bank` WHERE number = 348 AND name = '348 - BANCO XP S.A.'");
        await queryRunner.query("DELETE FROM `bank` WHERE number = 351 AND name = '351 - BANCO BOZANO SIMONSEN S.A.'");
        await queryRunner.query("DELETE FROM `bank` WHERE number = 353 AND name = '353 - BANCO GERAL DO COMERCIO S.A.'");
        await queryRunner.query("DELETE FROM `bank` WHERE number = 356 AND name = '356 - ABN AMRO S.A.'");
        await queryRunner.query("DELETE FROM `bank` WHERE number = 366 AND name = '366 - BANCO SOGERAL S.A.'");
        await queryRunner.query("DELETE FROM `bank` WHERE number = 369 AND name = '369 - PONTUAL'");
        await queryRunner.query("DELETE FROM `bank` WHERE number = 370 AND name = '370 - BEAL - BANCO EUROPEU PARA AMERICA LATINA'");
        await queryRunner.query("DELETE FROM `bank` WHERE number = 372 AND name = '372 - BANCO ITAMARATI S.A.'");
        await queryRunner.query("DELETE FROM `bank` WHERE number = 375 AND name = '375 - BANCO FENICIA S.A.'");
        await queryRunner.query("DELETE FROM `bank` WHERE number = 376 AND name = '376 - CHASE MANHATTAN BANK S.A.'");
        await queryRunner.query("DELETE FROM `bank` WHERE number = 386 AND name = '386 - NU FINANCEIRA S.A. - Sociedade de Crédito, Financiamento e Investimento'");
        await queryRunner.query("DELETE FROM `bank` WHERE number = 388 AND name = '388 - BANCO MERCANTIL DE DESCONTOS S/A'");
        await queryRunner.query("DELETE FROM `bank` WHERE number = 389 AND name = '389 - BANCO MERCANTIL DO BRASIL S.A.'");
        await queryRunner.query("DELETE FROM `bank` WHERE number = 392 AND name = '392 - BANCO MERCANTIL DE SAO PAULO S.A.'");
        await queryRunner.query("DELETE FROM `bank` WHERE number = 394 AND name = '394 - BANCO B.M.C. S.A.'");
        await queryRunner.query("DELETE FROM `bank` WHERE number = 399 AND name = '399 - BANCO BAMERINDUS DO BRASIL S.A.'");
        await queryRunner.query("DELETE FROM `bank` WHERE number = 409 AND name = '409 - UNIBANCO - UNIAO DOS BANCOS BRASILEIROS'");
        await queryRunner.query("DELETE FROM `bank` WHERE number = 412 AND name = '412 - BANCO NACIONAL DA BAHIA S.A.'");
        await queryRunner.query("DELETE FROM `bank` WHERE number = 415 AND name = '415 - BANCO NACIONAL S.A.'");
        await queryRunner.query("DELETE FROM `bank` WHERE number = 420 AND name = '420 - BANCO NACIONAL DO NORTE S.A.'");
        await queryRunner.query("DELETE FROM `bank` WHERE number = 422 AND name = '422 - BANCO SAFRA S.A.'");
        await queryRunner.query("DELETE FROM `bank` WHERE number = 424 AND name = '424 - BANCO NOROESTE S.A.'");
        await queryRunner.query("DELETE FROM `bank` WHERE number = 434 AND name = '434 - BANCO FORTALEZA S.A.'");
        await queryRunner.query("DELETE FROM `bank` WHERE number = 453 AND name = '453 - BANCO RURAL S.A.'");
        await queryRunner.query("DELETE FROM `bank` WHERE number = 456 AND name = '456 - BANCO TOKIO S.A.'");
        await queryRunner.query("DELETE FROM `bank` WHERE number = 464 AND name = '464 - BANCO SUMITOMO BRASILEIRO S.A.'");
        await queryRunner.query("DELETE FROM `bank` WHERE number = 466 AND name = '466 - BANCO MITSUBISHI BRASILEIRO S.A.'");
        await queryRunner.query("DELETE FROM `bank` WHERE number = 472 AND name = '472 - LLOYDS BANK PLC'");
        await queryRunner.query("DELETE FROM `bank` WHERE number = 473 AND name = '473 - BANCO FINANCIAL PORTUGUES S.A.'");
        await queryRunner.query("DELETE FROM `bank` WHERE number = 477 AND name = '477 - CITIBANK N.A.'");
        await queryRunner.query("DELETE FROM `bank` WHERE number = 479 AND name = '479 - BANCO DE BOSTON S.A.'");
        await queryRunner.query("DELETE FROM `bank` WHERE number = 480 AND name = '480 - BANCO PORTUGUES DO ATLANTICO-BRASIL S.A.'");
        await queryRunner.query("DELETE FROM `bank` WHERE number = 483 AND name = '483 - BANCO AGRIMISA S.A.'");
        await queryRunner.query("DELETE FROM `bank` WHERE number = 487 AND name = '487 - DEUTSCHE BANK S.A - BANCO ALEMAO'");
        await queryRunner.query("DELETE FROM `bank` WHERE number = 488 AND name = '488 - BANCO J. P. MORGAN S.A.'");
        await queryRunner.query("DELETE FROM `bank` WHERE number = 489 AND name = '489 - BANESTO BANCO URUGAUAY S.A.'");
        await queryRunner.query("DELETE FROM `bank` WHERE number = 492 AND name = '492 - INTERNATIONALE NEDERLANDEN BANK N.V.'");
        await queryRunner.query("DELETE FROM `bank` WHERE number = 493 AND name = '493 - BANCO UNION S.A.C.A.'");
        await queryRunner.query("DELETE FROM `bank` WHERE number = 494 AND name = '494 - BANCO LA REP. ORIENTAL DEL URUGUAY'");
        await queryRunner.query("DELETE FROM `bank` WHERE number = 495 AND name = '495 - BANCO LA PROVINCIA DE BUENOS AIRES'");
        await queryRunner.query("DELETE FROM `bank` WHERE number = 496 AND name = '496 - BANCO EXTERIOR DE ESPANA S.A.'");
        await queryRunner.query("DELETE FROM `bank` WHERE number = 498 AND name = '498 - CENTRO HISPANO BANCO'");
        await queryRunner.query("DELETE FROM `bank` WHERE number = 499 AND name = '499 - BANCO IOCHPE S.A.'");
        await queryRunner.query("DELETE FROM `bank` WHERE number = 501 AND name = '501 - BANCO BRASILEIRO IRAQUIANO S.A.'");
        await queryRunner.query("DELETE FROM `bank` WHERE number = 502 AND name = '502 - BANCO SANTANDER S.A.'");
        await queryRunner.query("DELETE FROM `bank` WHERE number = 504 AND name = '504 - BANCO MULTIPLIC S.A.'");
        await queryRunner.query("DELETE FROM `bank` WHERE number = 505 AND name = '505 - BANCO GARANTIA S.A.'");
        await queryRunner.query("DELETE FROM `bank` WHERE number = 600 AND name = '600 - BANCO LUSO BRASILEIRO S.A.'");
        await queryRunner.query("DELETE FROM `bank` WHERE number = 601 AND name = '601 - BFC BANCO S.A.'");
        await queryRunner.query("DELETE FROM `bank` WHERE number = 602 AND name = '602 - BANCO PATENTE S.A.'");
        await queryRunner.query("DELETE FROM `bank` WHERE number = 604 AND name = '604 - BANCO INDUSTRIAL DO BRASIL S.A.'");
        await queryRunner.query("DELETE FROM `bank` WHERE number = 607 AND name = '607 - BANCO SANTOS NEVES S.A.'");
        await queryRunner.query("DELETE FROM `bank` WHERE number = 608 AND name = '608 - BANCO OPEN S.A.'");
        await queryRunner.query("DELETE FROM `bank` WHERE number = 610 AND name = '610 - BANCO V.R. S.A.'");
        await queryRunner.query("DELETE FROM `bank` WHERE number = 611 AND name = '611 - BANCO PAULISTA S.A.'");
        await queryRunner.query("DELETE FROM `bank` WHERE number = 612 AND name = '612 - BANCO GUANABARA S.A.'");
        await queryRunner.query("DELETE FROM `bank` WHERE number = 613 AND name = '613 - OMNI BANCO S.A.'");
        await queryRunner.query("DELETE FROM `bank` WHERE number = 616 AND name = '616 - BANCO INTERPACIFICO S.A.'");
        await queryRunner.query("DELETE FROM `bank` WHERE number = 617 AND name = '617 - BANCO INVESTOR S.A.'");
        await queryRunner.query("DELETE FROM `bank` WHERE number = 618 AND name = '618 - BANCO TENDENCIA S.A.'");
        await queryRunner.query("DELETE FROM `bank` WHERE number = 621 AND name = '621 - BANCO APLICAP S.A.'");
        await queryRunner.query("DELETE FROM `bank` WHERE number = 622 AND name = '622 - BANCO DRACMA S.A.'");
        await queryRunner.query("DELETE FROM `bank` WHERE number = 623 AND name = '623 - BANCO PAN S.A.'");
        await queryRunner.query("DELETE FROM `bank` WHERE number = 624 AND name = '624 - BANCO GENERAL MOTORS S.A.'");
        await queryRunner.query("DELETE FROM `bank` WHERE number = 625 AND name = '625 - BANCO ARAUCARIA S.A.'");
        await queryRunner.query("DELETE FROM `bank` WHERE number = 626 AND name = '626 - BANCO C6 CONSIGNADO S.A.'");
        await queryRunner.query("DELETE FROM `bank` WHERE number = 627 AND name = '627 - BANCO DESTAK S.A.'");
        await queryRunner.query("DELETE FROM `bank` WHERE number = 628 AND name = '628 - BANCO CRITERIUM S.A.'");
        await queryRunner.query("DELETE FROM `bank` WHERE number = 629 AND name = '629 - BANCORP BANCO COML. E. DE INVESTMENTO'");
        await queryRunner.query("DELETE FROM `bank` WHERE number = 630 AND name = '630 - BANCO INTERCAP S.A.'");
        await queryRunner.query("DELETE FROM `bank` WHERE number = 633 AND name = '633 - BANCO REDIMENTO S.A.'");
        await queryRunner.query("DELETE FROM `bank` WHERE number = 634 AND name = '634 - BANCO TRIANGULO S.A.'");
        await queryRunner.query("DELETE FROM `bank` WHERE number = 635 AND name = '635 - BANCO DO ESTADO DO AMAPA S.A.'");
        await queryRunner.query("DELETE FROM `bank` WHERE number = 637 AND name = '637 - BANCO SOFISA S.A.'");
        await queryRunner.query("DELETE FROM `bank` WHERE number = 638 AND name = '638 - BANCO PROSPER S.A.'");
        await queryRunner.query("DELETE FROM `bank` WHERE number = 639 AND name = '639 - BIG S.A. - BANCO IRMAOS GUIMARAES'");
        await queryRunner.query("DELETE FROM `bank` WHERE number = 640 AND name = '640 - BANCO DE CREDITO METROPOLITANO S.A.'");
        await queryRunner.query("DELETE FROM `bank` WHERE number = 641 AND name = '641 - BANCO EXCEL ECONOMICO S/A'");
        await queryRunner.query("DELETE FROM `bank` WHERE number = 643 AND name = '643 - BANCO SEGMENTO S.A.'");
        await queryRunner.query("DELETE FROM `bank` WHERE number = 645 AND name = '645 - BANCO DO ESTADO DE RORAIMA S.A.'");
        await queryRunner.query("DELETE FROM `bank` WHERE number = 647 AND name = '647 - BANCO MARKA S.A.'");
        await queryRunner.query("DELETE FROM `bank` WHERE number = 648 AND name = '648 - BANCO ATLANTIS S.A.'");
        await queryRunner.query("DELETE FROM `bank` WHERE number = 649 AND name = '649 - BANCO DIMENSAO S.A.'");
        await queryRunner.query("DELETE FROM `bank` WHERE number = 650 AND name = '650 - BANCO PEBB S.A.'");
        await queryRunner.query("DELETE FROM `bank` WHERE number = 652 AND name = '652 - BANCO FRANCES E BRASILEIRO SA'");
        await queryRunner.query("DELETE FROM `bank` WHERE number = 653 AND name = '653 - BANCO INDUSVAL S.A.'");
        await queryRunner.query("DELETE FROM `bank` WHERE number = 654 AND name = '654 - BANCO A. J. RENNER S.A.'");
        await queryRunner.query("DELETE FROM `bank` WHERE number = 655 AND name = '655 - BANCO VOTORANTIM S.A.'");
        await queryRunner.query("DELETE FROM `bank` WHERE number = 656 AND name = '656 - BANCO MATRIX S.A.'");
        await queryRunner.query("DELETE FROM `bank` WHERE number = 657 AND name = '657 - BANCO TECNICORP S.A.'");
        await queryRunner.query("DELETE FROM `bank` WHERE number = 658 AND name = '658 - BANCO PORTO REAL S.A.'");
        await queryRunner.query("DELETE FROM `bank` WHERE number = 702 AND name = '702 - BANCO SANTOS S.A.'");
        await queryRunner.query("DELETE FROM `bank` WHERE number = 705 AND name = '705 - BANCO INVESTCORP S.A.'");
        await queryRunner.query("DELETE FROM `bank` WHERE number = 707 AND name = '707 - BANCO DAYCOVAL S.A.'");
        await queryRunner.query("DELETE FROM `bank` WHERE number = 711 AND name = '711 - BANCO VETOR S.A.'");
        await queryRunner.query("DELETE FROM `bank` WHERE number = 713 AND name = '713 - BANCO CINDAM S.A.'");
        await queryRunner.query("DELETE FROM `bank` WHERE number = 715 AND name = '715 - BANCO VEGA S.A.'");
        await queryRunner.query("DELETE FROM `bank` WHERE number = 718 AND name = '718 - BANCO OPERADOR S.A.'");
        await queryRunner.query("DELETE FROM `bank` WHERE number = 719 AND name = '719 - BANCO PRIMUS S.A.'");
        await queryRunner.query("DELETE FROM `bank` WHERE number = 720 AND name = '720 - BANCO MAXINVEST S.A.'");
        await queryRunner.query("DELETE FROM `bank` WHERE number = 721 AND name = '721 - BANCO CREDIBEL S.A.'");
        await queryRunner.query("DELETE FROM `bank` WHERE number = 722 AND name = '722 - BANCO INTERIOR DE SAO PAULO S.A.'");
        await queryRunner.query("DELETE FROM `bank` WHERE number = 724 AND name = '724 - BANCO PORTO SEGURO S.A.'");
        await queryRunner.query("DELETE FROM `bank` WHERE number = 725 AND name = '725 - BANCO FINABANCO S.A.'");
        await queryRunner.query("DELETE FROM `bank` WHERE number = 726 AND name = '726 - BANCO UNIVERSAL S.A.'");
        await queryRunner.query("DELETE FROM `bank` WHERE number = 728 AND name = '728 - BANCO FITAL S.A.'");
        await queryRunner.query("DELETE FROM `bank` WHERE number = 729 AND name = '729 - BANCO FONTE S.A.'");
        await queryRunner.query("DELETE FROM `bank` WHERE number = 730 AND name = '730 - BANCO COMERCIAL PARAGUAYO S.A.'");
        await queryRunner.query("DELETE FROM `bank` WHERE number = 731 AND name = '731 - BANCO GNPP S.A.'");
        await queryRunner.query("DELETE FROM `bank` WHERE number = 732 AND name = '732 - BANCO PREMIER S.A.'");
        await queryRunner.query("DELETE FROM `bank` WHERE number = 733 AND name = '733 - BANCO NACOES S.A.'");
        await queryRunner.query("DELETE FROM `bank` WHERE number = 734 AND name = '734 - BANCO GERDAU S.A.'");
        await queryRunner.query("DELETE FROM `bank` WHERE number = 735 AND name = '735 - BACO POTENCIAL'");
        await queryRunner.query("DELETE FROM `bank` WHERE number = 736 AND name = '736 - BANCO UNITED S.A.'");
        await queryRunner.query("DELETE FROM `bank` WHERE number = 737 AND name = '737 - THECA'");
        await queryRunner.query("DELETE FROM `bank` WHERE number = 738 AND name = '738 - MARADA'");
        await queryRunner.query("DELETE FROM `bank` WHERE number = 739 AND name = '739 - BGN'");
        await queryRunner.query("DELETE FROM `bank` WHERE number = 740 AND name = '740 - BCN BARCLAYS'");
        await queryRunner.query("DELETE FROM `bank` WHERE number = 741 AND name = '741 - BRP'");
        await queryRunner.query("DELETE FROM `bank` WHERE number = 742 AND name = '742 - EQUATORIAL'");
        await queryRunner.query("DELETE FROM `bank` WHERE number = 743 AND name = '743 - BANCO EMBLEMA S.A.'");
        await queryRunner.query("DELETE FROM `bank` WHERE number = 744 AND name = '744 - THE FIRST NATIONAL BANK OF BOSTON'");
        await queryRunner.query("DELETE FROM `bank` WHERE number = 745 AND name = '745 - CITIBAN N.A.'");
        await queryRunner.query("DELETE FROM `bank` WHERE number = 746 AND name = '746 - MODAL S\A'");
        await queryRunner.query("DELETE FROM `bank` WHERE number = 747 AND name = '747 - RAIBOBANK DO BRASIL'");
        await queryRunner.query("DELETE FROM `bank` WHERE number = 748 AND name = '748 - SICREDI'");
        await queryRunner.query("DELETE FROM `bank` WHERE number = 749 AND name = '749 - BRMSANTIL SA'");
        await queryRunner.query("DELETE FROM `bank` WHERE number = 750 AND name = '750 - BANCO REPUBLIC NATIONAL OF NEW YORK (BRA'");
        await queryRunner.query("DELETE FROM `bank` WHERE number = 751 AND name = '751 - DRESDNER BANK LATEINAMERIKA-BRASIL S/A'");
        await queryRunner.query("DELETE FROM `bank` WHERE number = 752 AND name = '752 - BANCO BANQUE NATIONALE DE PARIS BRASIL S'");
        await queryRunner.query("DELETE FROM `bank` WHERE number = 753 AND name = '753 - BANCO COMERCIAL URUGUAI S.A.'");
        await queryRunner.query("DELETE FROM `bank` WHERE number = 755 AND name = '755 - BANCO MERRILL LYNCH S.A.'");
        await queryRunner.query("DELETE FROM `bank` WHERE number = 756 AND name = '756 - BANCO COOPERATIVO DO BRASIL S.A.'");
        await queryRunner.query("DELETE FROM `bank` WHERE number = 757 AND name = '757 - BANCO KEB DO BRASIL S.A.'");
    }

}
